### ISSUE TITLE
Token is not listed in the wallet [NVL]

### ISSUE THREAD

**Issue by rebelC0der** [MELD-labs/meld-supported-config#70]
Can someone please check, why NVL token is not listed in the wallet?

It has been added and merged in the following PR: https://github.com/MELD-labs/meld-supported-config/pull/69

```
{
    "CMCslug": "",
    "decimals": 6,
    "mldId": "cardano-NVL-5b26e685cc5c9ad630bde3e3cd48c694436671f3d25df53777ca60ef4e564c",
    "orgName": "Nuvola Digital",
    "orgUrl": "https://www.nuvoladigital.io",
    "tokenAddress": "5b26e685cc5c9ad630bde3e3cd48c694436671f3d25df53777ca60ef4e564c",
    "tokenColorTheme": 16,
    "tokenIcon": "/static/tokens/NVL.svg",
    "tokenName": "NVL",
    "tokenTicker": "NVL",
    "tokenType": "CNT",
    "tags": []
}
```

https://cexplorer.io/asset/asset1jle4pt4cg8264ypx4u45vt99haa6ty3t7naxer

All other tokens from the same PR are listed.

**Comment by thuyvu17** [comment]
it's listed in the supported token https://tracking-api.meld.com/v1/tokens
could you please give me your address for further check?

**Comment by rebelC0der** [comment]
Yes, it is listed. metadata and asset is there. But it is not listed in the wallet. How can I send you my address privately?

**Comment by thuyvu17** [comment]
yes. you can send me via thuy@meld.com

**Comment by rebelC0der** [comment]
Done.

**Comment by infrmtcs** [comment]
Hi @rebelC0der, most of your assets are on the address you sent, but the reported token is actually stored in a different address. Please check the "Addresses" tab in your address page on cexplorer (`https://cexplorer.io/address/<your_address>/list#data`), you'll see another address containing some Ada and your NVL tokens.
The reason why cexplorer reports those tokens as your address's assets because it search by the staking credential of the address. Both of the addresses share the same staking credential.

**Comment by rebelC0der** [comment]
@infrmtcs I actually also just confirmed this, while I was waiting for you to check. I had a suspicion that this was the case. NVL tokens are staked, yes. And I guess, that moved them to a separate address. World Mobile has the same staking mechanism, where we stake them, but they are still in the users custody. Those tokens are listed correctly.

Do you think this is something MELD should add? Tokens are in the custody, but not displayed. A lot of CNTs have this mechanism of liquid, self-custodial staking. I would argue this is an important thing to support.
